#[derive(Clone, Copy)]
pub enum Key {
    Esc,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Num0,
    Minus,
    Equal,
    Backspace,
    Tab,
    W,
    Q,
    E,
    R,
    T,
    Y,
    U,
    I,
    O,
    P,
    LeftBrace,
    RightBrace,
    Enter,
    LeftCtrl,
    A,
    S,
    D,
    F,
    G,
    H,
    J,
    K,
    L,
    Semicolon,
    Apostrophe,
    Grave,
    LeftShift,
    Backslash,
    Z,
    X,
    C,
    V,
    B,
    N,
    M,
    Comma,
    Dot,
    Slash,
    RightShift,
    KpAsterisk,
    LeftAlt,
    Space,
    CapsLock,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    NumLock,
    ScrollLock,
    F11,
    F12,
    RightAlt,
    Home,
    Up,
    PageUp,
    Left,
    Right,
    End,
    Down,
    PageDown,
    Insert,
    Delete,
    Mute,
    VolumeDown,
    VolumeUp,
    Power,
    Pause,
}

impl Key {
    pub fn value(&self) -> u16 {
        match self {
            Self::Esc => 1,
            Self::Num1 => 2,
            Self::Num2 => 3,
            Self::Num3 => 4,
            Self::Num4 => 5,
            Self::Num5 => 6,
            Self::Num6 => 7,
            Self::Num7 => 8,
            Self::Num8 => 9,
            Self::Num9 => 10,
            Self::Num0 => 11,
            Self::Minus => 12,
            Self::Equal => 13,
            Self::Backspace => 14,
            Self::Tab => 15,
            Self::Q => 16,
            Self::W => 17,
            Self::E => 18,
            Self::R => 19,
            Self::T => 20,
            Self::Y => 21,
            Self::U => 22,
            Self::I => 23,
            Self::O => 24,
            Self::P => 25,
            Self::LeftBrace => 26,
            Self::RightBrace => 27,
            Self::Enter => 28,
            Self::LeftCtrl => 29,
            Self::A => 30,
            Self::S => 31,
            Self::D => 32,
            Self::F => 33,
            Self::G => 34,
            Self::H => 35,
            Self::J => 36,
            Self::K => 37,
            Self::L => 38,
            Self::Semicolon => 39,
            Self::Apostrophe => 40,
            Self::Grave => 41,
            Self::LeftShift => 42,
            Self::Backslash => 43,
            Self::Z => 44,
            Self::X => 45,
            Self::C => 46,
            Self::V => 47,
            Self::B => 48,
            Self::N => 49,
            Self::M => 50,
            Self::Comma => 51,
            Self::Dot => 52,
            Self::Slash => 53,
            Self::RightShift => 54,
            Self::KpAsterisk => 55,
            Self::LeftAlt => 56,
            Self::Space => 57,
            Self::CapsLock => 58,
            Self::F1 => 59,
            Self::F2 => 60,
            Self::F3 => 61,
            Self::F4 => 62,
            Self::F5 => 63,
            Self::F6 => 64,
            Self::F7 => 65,
            Self::F8 => 66,
            Self::F9 => 67,
            Self::F10 => 68,
            Self::NumLock => 69,
            Self::ScrollLock => 70,
            Self::F11 => 87,
            Self::F12 => 88,
            Self::RightAlt => 100,
            Self::Home => 102,
            Self::Up => 103,
            Self::PageUp => 104,
            Self::Left => 105,
            Self::Right => 106,
            Self::End => 107,
            Self::Down => 108,
            Self::PageDown => 109,
            Self::Insert => 110,
            Self::Delete => 111,
            Self::Mute => 113,
            Self::VolumeDown => 114,
            Self::VolumeUp => 115,
            Self::Power => 116,
            Self::Pause => 119,
        }
    }
}
